# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170729_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
