# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171107_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentitem',
            name='user',
            field=models.IntegerField(),
        ),
    ]
