# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171107_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentitem',
            name='begin_disp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rentitem',
            name='end_disp',
            field=models.DateField(null=True),
        ),
    ]
